/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'U0127650' at '1/13/18 3:13 PM' with Gradle 3.1
 *
 * @author U0127650, @date 1/13/18 3:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
