package baoying;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'U0127650' at '1/13/18 3:13 PM' with Gradle 3.1
 *
 * @author U0127650, @date 1/13/18 3:13 PM
 */
public class Main {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args){

        System.out.println("this lib is for lib evaluation");

    }
}
