package baoying;

import baoying.Main;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'U0127650' at '1/13/18 3:13 PM' with Gradle 3.1
 *
 * @author U0127650, @date 1/13/18 3:13 PM
 */
public class MainTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
